import {
  LayoutDashboard,
  Plus,
  CalendarDays,
  CreditCard,
  Settings,
  Bell,
  LogOut,
  ChevronRight,
  AlertTriangle,
  CheckCircle2,
  X,
  Search,
  Zap,
  Trash2,
  ExternalLink,
  Menu,
  User,
  Share2,
  Download,
  Tv,
  Briefcase,
  Receipt,
  Coffee,
  MoreVertical,
  TrendingUp,
  RefreshCw,
  HelpCircle,
  Lock,
  ShieldCheck,
  ShieldAlert,
  Globe,
  Smartphone,
  Check,
  ArrowRight
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Add: Plus,
  Calendar: CalendarDays,
  Card: CreditCard,
  Settings: Settings,
  Bell: Bell,
  Logout: LogOut,
  ChevronRight: ChevronRight,
  Warning: AlertTriangle,
  Check: CheckCircle2,
  Close: X,
  Search: Search,
  Zap: Zap,
  Delete: Trash2,
  Link: ExternalLink,
  Menu: Menu,
  User: User,
  Share: Share2,
  Download: Download,
  More: MoreVertical,
  TrendingUp: TrendingUp,
  RefreshCw: RefreshCw,
  Lock: Lock,
  ShieldCheck: ShieldCheck,
  ShieldAlert: ShieldAlert,
  Globe: Globe,
  Smartphone: Smartphone,
  CheckRaw: Check,
  ArrowRight: ArrowRight,
  // Categories
  Entertainment: Tv,
  Work: Briefcase,
  Bills: Receipt,
  Lifestyle: Coffee,
  Other: HelpCircle
};